[settings]
experimental = true
python.uv_venv_auto = true

[env]
TB_PROJECT_SOURCE = "repolish"

[tools]
uv = "0.7.20"
dprint = "0.50.1"
starship = "1.23.0"

[hooks]
postinstall = [
  "uvx pkglink sync",
  "poe setup-hook",
]
