"""Adopt developer-edited insertion markers into template-managed output.

Template-rendered files are regenerated on every apply, which would normally
reset each insertion marker to the template's defaults and stomp any edits the
developer made to the marker's function or args.

This module reconciles the two sources during preprocessing: for every
insertion block present in the rendered content, the opening marker from the
matching block in the local file is spliced in, so the insertion phase fills
the body from the developer's chosen function and parameters.

Matching is by tag and occurrence order, mirroring keep-block pairing: the
template (or rendered output) decides *where* blocks live; the local file
decides *how* each block is filled. The block body is never adopted — insertion
bodies are always regenerated by the insertion phase.
"""

from __future__ import annotations

from hotlog import get_logger

from repolish.insertions.parser import parse_text
from repolish.marker_kit import apply_splices, pair_in_occurrence_order

logger = get_logger(__name__)


def adopt_local_insertion_markers(
    rendered_content: str,
    local_content: str,
    *,
    source_path: str | None = None,
) -> str:
    """Splice local opening markers into rendered content for shared tags.

    Args:
        rendered_content: The template output (post-render) being reconciled.
        local_content: The current on-disk file content to adopt markers from.
        source_path: Optional path used for contextual debug logs.

    Returns:
        The rendered content with local opening markers adopted where a block
        with the same tag exists in the local file. Content is returned
        unchanged when either side has no insertion blocks.
    """
    if 'repolish:' not in rendered_content or 'repolish:' not in local_content:
        return rendered_content

    rendered = parse_text(rendered_content, file_path=source_path or '')
    local = parse_text(local_content, file_path=source_path or '')
    if not rendered.blocks or not local.blocks:
        return rendered_content

    pairs = pair_in_occurrence_order(
        rendered.blocks,
        local.blocks,
        key=lambda block: block.tag,
    )

    splices: list[tuple[int, int, str]] = []
    adopted_tags: list[str] = []
    for block, local_block in pairs:
        marker = local_content[local_block.start : local_block.body_start]
        if marker == rendered_content[block.start : block.body_start]:
            continue
        splices.append((block.start, block.body_start, marker))
        adopted_tags.append(block.tag)

    if not splices:
        return rendered_content

    logger.debug(
        'adopted_local_insertion_markers',
        tags=adopted_tags,
        source_path=source_path,
    )
    return apply_splices(rendered_content, splices)
