"""Tests for the generated provider CLI: ``provider_cli`` and ``run_lane``.

A fixture provider package (modeled on the github-actions example from the
fast lanes design) is staged on disk with real ``repolish.yaml`` project
configs, so these cover the production path: config discovery, alias
resolution, the single-provider pipeline with the dry pass skipped, and the
parity guarantee against a full ``repolish apply``.
"""

from __future__ import annotations

import importlib
from typing import TYPE_CHECKING

import pytest
import yaml

from repolish.cli.testing import CliRunner
from repolish.commands.apply.options import ApplyOptions
from repolish.commands.apply.session import run_session
from repolish.fastlane import provider_cli
from tests.testing.test_e2e import _make_provider_pkg

if TYPE_CHECKING:
    from pathlib import Path

    import cyclopts

runner = CliRunner()

LaneCli = tuple['cyclopts.App', 'Path', type]
"""The lane_cli fixture tuple: (app, staged project dir, provider class)."""

_LANE_PROVIDER = """\
    from repolish import BaseContext, BaseInputs, FastLaneSpec, Provider, TemplateMapping

    class Ctx(BaseContext):
        pass


    def _usage():
        return 'usage: demo-cli actions'


    class P(Provider[Ctx, BaseInputs]):
        def create_context(self):
            return Ctx()

        def create_file_mappings(self, context):
            return {'.github/workflows/ci.yml': 'ci.yml.jinja'}

        def create_fast_lanes(self, repolish):
            header = f'# generated by {repolish.provider.alias}'
            return {
                'actions': FastLaneSpec(
                    file_mappings={
                        'action1/action.yaml': TemplateMapping(
                            '_repolish.action.yaml.jinja',
                            extra_context={'module': 'action1.main', 'header': header},
                        ),
                        'plain.txt': 'plain.txt.jinja',
                    },
                ),
                'docs': FastLaneSpec(
                    file_insertions={'README.md': {'render-usage': _usage}},
                ),
            }
    """

_TEMPLATES = {
    'ci.yml.jinja': 'name: CI\n',
    '_repolish.action.yaml.jinja': ('{{ header }}\nruns: uvx --from {{ module }}\n'),
    'plain.txt.jinja': 'plain output\n',
}

_COMMAND_PROVIDER = """\
    from pydantic import BaseModel

    from repolish import (
        BaseContext,
        BaseInputs,
        FastLaneSpec,
        Provider,
        ProviderCommandContract,
        ProviderCommandContext,
        TemplateMapping,
    )

    class Ctx(BaseContext):
        pass


    class FetchArgs(BaseModel):
        name: str
        style: str = 'classic'


    def run_fetch(args: FetchArgs, ctx: ProviderCommandContext) -> FastLaneSpec:
        return FastLaneSpec(
            file_mappings={
                'data.json': TemplateMapping(
                    '_repolish.data.json.jinja',
                    extra_context={'name': args.name, 'style': args.style, 'alias': ctx.repolish.provider.alias},
                ),
            },
        )


    class P(Provider[Ctx, BaseInputs]):
        def create_context(self):
            return Ctx()

        def create_fast_lanes(self, repolish):
            return {
                'actions': FastLaneSpec(
                    file_mappings={'plain.txt': 'plain.txt.jinja'},
                ),
                'report': lambda: FastLaneSpec(
                    file_mappings={'report.txt': 'report.txt.jinja'},
                ),
            }

        @classmethod
        def create_provider_commands(cls):
            return {
                'fetch': ProviderCommandContract(
                    args_model=FetchArgs,
                    executor=run_fetch,
                    summary='Fetch remote metadata',
                ),
            }
"""

_COMMAND_TEMPLATES = {
    'plain.txt.jinja': 'plain output\n',
    '_repolish.data.json.jinja': 'fetched: yes\n',
    'report.txt.jinja': 'report output\n',
}

_STRING_MAPPING_COMMAND_PROVIDER = """\
    from pydantic import BaseModel

    from repolish import (
        BaseContext,
        BaseInputs,
        FastLaneSpec,
        Provider,
        ProviderCommandContract,
        ProviderCommandContext,
    )

    class Ctx(BaseContext):
        pass


    class FetchArgs(BaseModel):
        name: str


    def run_fetch(args: FetchArgs, ctx: ProviderCommandContext) -> FastLaneSpec:
        return FastLaneSpec(
            file_mappings={
                'data.txt': 'plain.txt.jinja',
            },
        )


    class P(Provider[Ctx, BaseInputs]):
        def create_context(self):
            return Ctx()

        @classmethod
        def create_provider_commands(cls):
            return {
                'fetch': ProviderCommandContract(
                    args_model=FetchArgs,
                    executor=run_fetch,
                    summary='String mapping command',
                ),
            }
"""

_COLLIDING_NAMES_PROVIDER = """\
    from pydantic import BaseModel

    from repolish import (
        BaseContext,
        BaseInputs,
        FastLaneSpec,
        Provider,
        ProviderCommandContract,
    )

    class Ctx(BaseContext):
        pass


    class FetchArgs(BaseModel):
        name: str


    def run_actions(args: FetchArgs, _ctx):
        return FastLaneSpec()


    class P(Provider[Ctx, BaseInputs]):
        def create_context(self):
            return Ctx()

        def create_fast_lanes(self, repolish):
            return {
                'actions': FastLaneSpec(),
            }

        @classmethod
        def create_provider_commands(cls):
            return {
                'actions': ProviderCommandContract(
                    args_model=FetchArgs,
                    executor=run_actions,
                    summary='Intentional collision',
                ),
            }
"""


def _stage_project(
    provider_cls: type,
    base: Path,
    *,
    extra_config: dict | None = None,
    alias: str = 'demo',
) -> Path:
    """Write a project dir whose repolish.yaml registers *provider_cls*."""
    provider_root = base / 'pkg' / 'resources' / 'templates'
    project = base / 'project'
    project.mkdir()
    (project / 'README.md').write_text(
        'intro\n\n<!-- repolish:on:usage render-usage -->\n<!-- repolish:off:usage -->\n',
        encoding='utf-8',
    )
    config_data = {
        'providers': {alias: {'provider_root': str(provider_root)}},
        **(extra_config or {}),
    }
    (project / 'repolish.yaml').write_text(
        yaml.safe_dump(config_data),
        encoding='utf-8',
    )
    return project


@pytest.fixture
def lane_cli(tmp_path: Path):
    """A provider with two lanes plus its generated CLI and staged project."""
    provider_cls = _make_provider_pkg(
        tmp_path,
        _LANE_PROVIDER,
        templates=_TEMPLATES,
    )
    app = provider_cli(provider_cls)
    project = _stage_project(provider_cls, tmp_path)
    return app, project, provider_cls


class TestSubcommands:
    def test_subcommands_come_from_create_fast_lanes(
        self,
        lane_cli: LaneCli,
    ) -> None:
        app, _, _ = lane_cli

        result = runner.invoke(app, ['--help'])

        assert result.exit_code == 0
        for name in ('actions', 'docs', 'all'):
            assert name in result.output

    def test_lane_subcommand_runs_only_lane_contributions(
        self,
        lane_cli: LaneCli,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        app, project, _ = lane_cli
        monkeypatch.chdir(project)

        result = runner.invoke(app, ['actions'])

        assert result.exit_code == 0, result.output
        # the lane hook built its header from the injected provider identity
        assert (project / 'action1' / 'action.yaml').read_text(
            encoding='utf-8',
        ) == ('# generated by demo\nruns: uvx --from action1.main\n')
        # regular-hook mapping did not run
        assert not (project / '.github' / 'workflows' / 'ci.yml').exists()
        # docs-lane insertion did not run
        assert 'usage: demo-cli actions' not in (project / 'README.md').read_text(encoding='utf-8')

    def test_all_subcommand_merges_lanes_and_regular(
        self,
        lane_cli: LaneCli,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        app, project, _ = lane_cli
        monkeypatch.chdir(project)

        result = runner.invoke(app, ['all'])

        assert result.exit_code == 0, result.output
        assert (project / 'action1' / 'action.yaml').exists()
        assert (project / '.github' / 'workflows' / 'ci.yml').exists()
        assert 'usage: demo-cli actions' in (project / 'README.md').read_text(
            encoding='utf-8',
        )

    def test_docs_lane_runs_only_insertions(
        self,
        lane_cli: LaneCli,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        app, project, _ = lane_cli
        monkeypatch.chdir(project)

        result = runner.invoke(app, ['docs'])

        assert result.exit_code == 0, result.output
        readme = (project / 'README.md').read_text(encoding='utf-8')
        assert 'usage: demo-cli actions' in readme
        assert not (project / 'action1' / 'action.yaml').exists()


class TestConfigHandling:
    def test_paused_files_from_real_config_are_honored(
        self,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        provider_cls = _make_provider_pkg(
            tmp_path,
            _LANE_PROVIDER,
            templates=_TEMPLATES,
        )
        app = provider_cli(provider_cls)
        project = _stage_project(
            provider_cls,
            tmp_path,
            extra_config={'paused_files': ['plain.txt']},
        )
        monkeypatch.chdir(project)

        result = runner.invoke(app, ['actions'])

        assert result.exit_code == 0, result.output
        assert not (project / 'plain.txt').exists()
        assert (project / 'action1' / 'action.yaml').exists()

    def test_check_flag_compares_without_writing(
        self,
        lane_cli: LaneCli,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        app, project, _ = lane_cli
        monkeypatch.chdir(project)

        missing = runner.invoke(app, ['actions', '--check'])
        assert missing.exit_code == 2, missing.output
        assert not (project / 'action1' / 'action.yaml').exists()

        runner.invoke(app, ['actions'])
        clean = runner.invoke(app, ['actions', '--check'])
        assert clean.exit_code == 0, clean.output

    def test_runs_without_config_file(
        self,
        lane_cli: LaneCli,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        # A lane CLI is an extension of the provider package: it works in any
        # directory, registered or not. Without a repolish.yaml the run falls
        # back to the package name as the provider identity.
        app, _, _ = lane_cli
        empty = tmp_path / 'empty-project'
        empty.mkdir()
        monkeypatch.chdir(empty)

        result = runner.invoke(app, ['actions'])

        assert result.exit_code == 0, result.output
        assert (empty / 'action1' / 'action.yaml').read_text(
            encoding='utf-8',
        ) == ('# generated by pkg\nruns: uvx --from action1.main\n')

    def test_unlisted_provider_still_honors_project_keys(
        self,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        provider_cls = _make_provider_pkg(
            tmp_path,
            _LANE_PROVIDER,
            templates=_TEMPLATES,
        )
        app = provider_cli(provider_cls)
        project = tmp_path / 'project'
        project.mkdir()
        # The config registers some other provider; this CLI's package is not
        # listed. The lane still runs, and the project's paused_files apply.
        (project / 'repolish.yaml').write_text(
            yaml.safe_dump(
                {
                    'providers': {
                        'other': {'provider_root': '/definitely/not/this'},
                    },
                    'paused_files': ['plain.txt'],
                },
            ),
            encoding='utf-8',
        )
        monkeypatch.chdir(project)

        result = runner.invoke(app, ['actions'])

        assert result.exit_code == 0, result.output
        assert (project / 'action1' / 'action.yaml').exists()
        assert not (project / 'plain.txt').exists()  # paused_files honored


class TestAliasResolution:
    def test_alias_resolved_by_provider_root_match(
        self,
        lane_cli: LaneCli,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        # The staged config registers the provider under 'demo' with its
        # resources/templates path; the CLI must find that alias on its own.
        app, project, _ = lane_cli
        monkeypatch.chdir(project)

        result = runner.invoke(app, ['actions'])

        assert result.exit_code == 0, result.output

    def test_alias_override_wins(
        self,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        provider_cls = _make_provider_pkg(
            tmp_path,
            _LANE_PROVIDER,
            templates=_TEMPLATES,
        )
        app = provider_cli(provider_cls, alias='renamed')
        project = _stage_project(provider_cls, tmp_path, alias='renamed')
        monkeypatch.chdir(project)

        result = runner.invoke(app, ['actions'])

        assert result.exit_code == 0, result.output
        assert (project / 'action1' / 'action.yaml').exists()

    def test_alias_override_works_without_registration(
        self,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        # The alias is the provider-owned identity: it does not have to appear
        # in the project config, and it is what ends up in generated headers.
        provider_cls = _make_provider_pkg(
            tmp_path,
            _LANE_PROVIDER,
            templates=_TEMPLATES,
        )
        app = provider_cli(provider_cls, alias='ghost')
        project = _stage_project(provider_cls, tmp_path)  # registered as 'demo'
        monkeypatch.chdir(project)

        result = runner.invoke(app, ['actions'])

        assert result.exit_code == 0, result.output
        assert (project / 'action1' / 'action.yaml').read_text(
            encoding='utf-8',
        ) == ('# generated by ghost\nruns: uvx --from action1.main\n')


class TestProviderRootDiscovery:
    def test_provider_without_templates_dir_errors(
        self,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        # A provider package with a pyproject.toml but no resources/templates:
        # the walk must stop at the package root and say what is missing.
        pkg = tmp_path / 'rootless'
        pkg.mkdir()
        (pkg / 'pyproject.toml').write_text('[project]\n', encoding='utf-8')
        (pkg / 'mod.py').write_text(
            'from repolish import Provider\n\n\nclass Rootless(Provider):\n    pass\n',
            encoding='utf-8',
        )
        monkeypatch.syspath_prepend(tmp_path)
        mod = importlib.import_module('rootless.mod')

        with pytest.raises(RuntimeError, match='resources/templates'):
            provider_cli(mod.Rootless)


class TestParamParity:
    def test_lane_subcommands_expose_the_apply_flags(
        self,
        lane_cli: LaneCli,
    ) -> None:
        """Lane params derive from the apply CLI's model, so flags cannot drift."""
        app, _, _ = lane_cli

        result = runner.invoke(app, ['actions', '--help'])

        assert result.exit_code == 0, result.output
        for flag in (
            '--config',
            '--check',
            '--skip-post-process',
            '--fail-on-warnings',
        ):
            assert flag in result.output

    def test_lane_post_process_runs_and_skip_flag_honored(
        self,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        # A named lane runs only its own fast_lanes.config post_process
        # commands; the project's top-level post_process never applies.
        provider_cls = _make_provider_pkg(
            tmp_path,
            _LANE_PROVIDER,
            templates=_TEMPLATES,
        )
        app = provider_cli(provider_cls)
        project = _stage_project(
            provider_cls,
            tmp_path,
            extra_config={
                'post_process': ['touch project.txt'],
                'fast_lanes': {
                    'config': {'actions': {'post_process': ['touch lane.txt']}},
                },
            },
        )
        monkeypatch.chdir(project)

        skipped = runner.invoke(app, ['actions', '--skip-post-process'])
        assert skipped.exit_code == 0, skipped.output
        assert not (project / 'lane.txt').exists()

        applied = runner.invoke(app, ['actions'])
        assert applied.exit_code == 0, applied.output
        assert (project / 'lane.txt').exists()
        assert not (project / 'project.txt').exists()  # project commands skipped

    def test_lane_without_config_entry_runs_no_post_process(
        self,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        # The point of per-lane config: a lane with no entry runs nothing at
        # all, so a python-only lane never runs the project's dprint.
        provider_cls = _make_provider_pkg(
            tmp_path,
            _LANE_PROVIDER,
            templates=_TEMPLATES,
        )
        app = provider_cli(provider_cls)
        project = _stage_project(
            provider_cls,
            tmp_path,
            extra_config={'post_process': ['touch project.txt']},
        )
        monkeypatch.chdir(project)

        result = runner.invoke(app, ['actions'])

        assert result.exit_code == 0, result.output
        assert not (project / 'project.txt').exists()

    def test_all_subcommand_runs_project_post_process(
        self,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        # `all` mirrors a full provider pass: the project's commands apply.
        provider_cls = _make_provider_pkg(
            tmp_path,
            _LANE_PROVIDER,
            templates=_TEMPLATES,
        )
        app = provider_cli(provider_cls)
        project = _stage_project(
            provider_cls,
            tmp_path,
            extra_config={'post_process': ['touch project.txt']},
        )
        monkeypatch.chdir(project)

        result = runner.invoke(app, ['all'])

        assert result.exit_code == 0, result.output
        assert (project / 'project.txt').exists()


class TestParity:
    def test_lane_output_matches_full_apply_check(
        self,
        lane_cli: LaneCli,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        """The parity guarantee: a lane run then a full apply check has no drift."""
        app, project, _ = lane_cli
        monkeypatch.chdir(project)

        lane_run = runner.invoke(app, ['all'])
        assert lane_run.exit_code == 0, lane_run.output

        rc = run_session(
            ApplyOptions(
                config_path=project / 'repolish.yaml',
                check_only=True,
            ),
        )
        assert rc == 0


class TestProviderCommands:
    @pytest.fixture
    def command_cli(
        self,
        tmp_path: Path,
    ) -> tuple[cyclopts.App, Path]:
        provider_cls = _make_provider_pkg(
            tmp_path,
            _COMMAND_PROVIDER,
            templates=_COMMAND_TEMPLATES,
        )
        app = provider_cli(provider_cls)
        project = _stage_project(provider_cls, tmp_path)
        return app, project

    def test_command_subcommand_is_registered(
        self,
        command_cli: tuple[cyclopts.App, Path],
    ) -> None:
        app, _ = command_cli

        result = runner.invoke(app, ['--help'])

        assert result.exit_code == 0, result.output
        for name in ('actions', 'report', 'fetch', 'all'):
            assert name in result.output

    def test_command_help_shows_typed_args_and_apply_flags(
        self,
        command_cli: tuple[cyclopts.App, Path],
    ) -> None:
        app, _ = command_cli

        result = runner.invoke(app, ['fetch', '--help'])

        assert result.exit_code == 0, result.output
        for flag in (
            '--config',
            '--check',
            '--skip-post-process',
            '--name',
            '--style',
        ):
            assert flag in result.output

    def test_command_requires_declared_args(
        self,
        command_cli: tuple[cyclopts.App, Path],
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        app, project = command_cli
        monkeypatch.chdir(project)

        result = runner.invoke(app, ['fetch'])

        assert result.exit_code != 0
        assert 'requires an argument' in result.output.lower()

    def test_command_runs_standalone_spec(
        self,
        command_cli: tuple[cyclopts.App, Path],
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        app, project = command_cli
        monkeypatch.chdir(project)

        result = runner.invoke(
            app,
            ['fetch', '--name', 'drawer', '--style', 'modern'],
        )

        assert result.exit_code == 0, result.output
        assert (project / 'data.json').read_text(
            encoding='utf-8',
        ) == 'fetched: yes\n'
        # Standalone command run still excludes regular hook mappings.
        assert not (project / '.github' / 'workflows' / 'ci.yml').exists()

    def test_all_excludes_standalone_commands(
        self,
        command_cli: tuple[cyclopts.App, Path],
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        app, project = command_cli
        monkeypatch.chdir(project)

        result = runner.invoke(app, ['all'])

        assert result.exit_code == 0, result.output
        assert (project / 'plain.txt').exists()
        assert (project / 'report.txt').exists()
        assert not (project / 'data.json').exists()

    def test_command_string_mapping_is_normalized_and_rendered(
        self,
        tmp_path: Path,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        provider_cls = _make_provider_pkg(
            tmp_path,
            _STRING_MAPPING_COMMAND_PROVIDER,
            templates={'plain.txt.jinja': 'plain output\n'},
        )
        app = provider_cli(provider_cls)
        project = _stage_project(provider_cls, tmp_path)
        monkeypatch.chdir(project)

        result = runner.invoke(app, ['fetch', '--name', 'drawer'])

        assert result.exit_code == 0, result.output
        assert (project / 'data.txt').read_text(
            encoding='utf-8',
        ) == 'plain output\n'

    def test_provider_command_name_collision_with_lane_raises(
        self,
        tmp_path: Path,
    ) -> None:
        provider_cls = _make_provider_pkg(
            tmp_path,
            _COLLIDING_NAMES_PROVIDER,
            templates={},
        )

        with pytest.raises(
            ValueError,
            match='provider command names collide with fast lane names',
        ):
            provider_cli(provider_cls)


_COPIES_PROVIDER = """\
    from repolish import BaseContext, BaseInputs, FastLaneSpec, Provider, ResourceCopy

    class Ctx(BaseContext):
        pass


    class P(Provider[Ctx, BaseInputs]):
        def create_context(self):
            return Ctx()

        def create_fast_lanes(self, repolish):
            return {
                'assets': FastLaneSpec(
                    file_mappings={'gen/asset.txt': 'plain.txt.jinja'},
                    file_copies=[
                        ResourceCopy(source='static/lane.bin', target='gen/lane.bin'),
                    ],
                ),
            }
    """

_COPIES_TEMPLATES = {'plain.txt.jinja': 'plain output\n'}


@pytest.fixture
def copies_cli(tmp_path: Path):
    """A provider whose lane declares its own copy.

    The project config declares one regular copy for the same provider.
    """
    provider_cls = _make_provider_pkg(
        tmp_path,
        _COPIES_PROVIDER,
        templates=_COPIES_TEMPLATES,
    )
    static = tmp_path / 'pkg' / 'resources' / 'static'
    static.mkdir(parents=True)
    (static / 'lane.bin').write_bytes(b'lane static\n')
    (static / 'defaults.json').write_text('{}\n', encoding='utf-8')
    provider_root = tmp_path / 'pkg' / 'resources' / 'templates'
    project = tmp_path / 'project'
    project.mkdir()
    (project / 'repolish.yaml').write_text(
        yaml.safe_dump(
            {
                'providers': {
                    'demo': {
                        'provider_root': str(provider_root),
                        'copies': [
                            {
                                'source': 'static/defaults.json',
                                'target': 'defaults.json',
                            },
                        ],
                    },
                },
            },
        ),
        encoding='utf-8',
    )
    app = provider_cli(provider_cls)
    return app, project


class TestLaneCopies:
    def test_named_lane_runs_only_lane_declared_copies(
        self,
        copies_cli: tuple[cyclopts.App, Path],
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        app, project = copies_cli
        monkeypatch.chdir(project)

        result = runner.invoke(app, ['assets'])

        assert result.exit_code == 0, result.output
        # the lane's own copy and mapping materialized
        assert (project / 'gen' / 'lane.bin').read_bytes() == b'lane static\n'
        assert (project / 'gen' / 'asset.txt').exists()
        # the provider's configured copy set never collected or ran
        assert not (project / 'defaults.json').exists()

    def test_all_run_collects_config_copies_and_lane_copies(
        self,
        copies_cli: tuple[cyclopts.App, Path],
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        app, project = copies_cli
        monkeypatch.chdir(project)

        result = runner.invoke(app, ['all'])

        assert result.exit_code == 0, result.output
        # full pass: the provider's configured copies still materialize
        assert (project / 'defaults.json').exists()
        # merged-lane parity: the lane's copy runs in the full pass too
        assert (project / 'gen' / 'lane.bin').exists()
        assert (project / 'gen' / 'asset.txt').exists()
