"""Insert-zone directive processing: provider-branded insertion zones.

An insert-zone directive declares a provider-owned, provider-filled region in a
provider-rendered file, bounded by *branded* markers that read as part of the
document instead of the ``repolish:on:tag`` machinery comments:

    ## repolish:insert[badges] start="<!-- generated:badges:on" end="<!-- generated:badges:off -->"

    <!-- generated:badges:on my-org/my-repo style=flat -->
    _Default badge row for new projects._
    <!-- generated:badges:off -->

The family itself does very little: it strips the (phase-selected) directive
lines, leaves the branded markers and the template default body untouched —
that default is the insertion phase's fallback — and adopts the developer's
opening marker (args included) from the local file, mirroring keep-block
occurrence pairing. No fill happens here: filling the zone body with a provider
function is insertion-phase machinery (``repolish.insertions``), driven by the
:class:`InsertZoneDeclaration` ferry that file-level processing carries out to
the apply session.
"""

from __future__ import annotations

import ast
from dataclasses import dataclass
from typing import TYPE_CHECKING

from hotlog import get_logger

from repolish.directives.definitions import (
    INSERT_ZONE_DIRECTIVE_RE,
    DirectiveMapDefinition,
    extract_directive_map,
)
from repolish.directives.phases import split_directive_tag
from repolish.marker_kit import (
    RegionBoundary,
    find_prefixed_bounded_regions,
)

if TYPE_CHECKING:
    from collections.abc import Mapping

logger = get_logger(__name__)


@dataclass(frozen=True)
class InsertZoneSpec:
    """One declared insertion zone: boundary markers plus optional function."""

    boundary: RegionBoundary
    function: str | None


@dataclass(frozen=True)
class InsertZoneDeclaration:
    """A zone extracted from a template, ferried to the insertion phase.

    The declaration is the ferry payload: the destination path the zone's
    template renders into travels on the :class:`~repolish.directives.registry.FerriedItem`
    envelope, not here.
    """

    name: str
    spec: InsertZoneSpec


def _parse_quoted_literal(raw: str) -> str:
    """Parse a quoted directive literal."""
    value = ast.literal_eval(raw)
    if not isinstance(value, str):
        msg = 'insert zone directive values must be quoted strings'
        raise TypeError(msg)
    return value


def _parse_insert_zone_spec(
    start_raw: str,
    end_mode: str,
    end_raw: str,
    function_raw: str | None = None,
) -> InsertZoneSpec:
    """Parse a zone's bounds and optional default function from one directive."""
    start = _parse_quoted_literal(start_raw)
    end_value = _parse_quoted_literal(end_raw)
    boundary = (
        RegionBoundary(start=start, end=end_value)
        if end_mode == 'end'
        else RegionBoundary(start=start, end_regex=end_value)
    )
    function = _parse_quoted_literal(function_raw) if function_raw else None
    return InsertZoneSpec(boundary=boundary, function=function)


_INSERT_ZONE_EXTRACT_DEF = DirectiveMapDefinition(
    pattern=INSERT_ZONE_DIRECTIVE_RE,
    parse_value=_parse_insert_zone_spec,
)


def extract_insert_zones(
    content: str,
    phase: str,
    source_path: str | None = None,
) -> dict[str, InsertZoneSpec]:
    """Extract insert-zone directives from *content* for the selected *phase*."""
    return extract_directive_map(
        content,
        _INSERT_ZONE_EXTRACT_DEF,
        phase=phase,
        source_path=source_path,
    )


def extract_insert_zone_declarations(
    content: str,
    phase: str,
    source_path: str | None = None,
) -> tuple[InsertZoneDeclaration, ...]:
    """Extract zone declarations for the family's ferry hook (this phase only)."""
    return tuple(
        InsertZoneDeclaration(name=name, spec=spec)
        for name, spec in extract_insert_zones(
            content,
            phase,
            source_path=source_path,
        ).items()
    )


def adopt_local_insert_zones(
    content: str,
    local_content: str,
    zones: Mapping[str, InsertZoneSpec],
) -> str:
    """Splice local opening markers into *content*, keeping developer args.

    Zones are template-managed, so the rendered opening marker resets to the
    template's default every apply. Pairing rendered regions with local regions
    by occurrence order (same rule as keep blocks) restores the developer's
    edited marker line — typically its trailing args. The block body is never
    adopted: zone bodies are always regenerated by the insertion phase.
    """
    result_lines = content.splitlines(keepends=True)
    local_lines = local_content.splitlines(keepends=True)
    adopted = [name for name, spec in zones.items() if _adopt_zone_openings(result_lines, local_lines, spec)]
    if adopted:
        logger.debug('adopted_local_insert_zones', names=adopted)
    return ''.join(result_lines)


def _adopt_zone_openings(
    result_lines: list[str],
    local_lines: list[str],
    spec: InsertZoneSpec,
) -> bool:
    """Splice local opening markers for one zone into *result_lines* in place."""
    rendered_regions = find_prefixed_bounded_regions(
        result_lines,
        spec.boundary,
    )
    local_regions = find_prefixed_bounded_regions(local_lines, spec.boundary)
    adopted = False
    for index, region in enumerate(rendered_regions):
        if index >= len(local_regions):
            break
        local_opening = local_lines[local_regions[index].start]
        if local_opening != result_lines[region.start]:
            result_lines[region.start] = local_opening
            adopted = True
    return adopted


def apply_insert_zones(
    content: str,
    zones: dict[str, InsertZoneSpec],
    local_content: str,
    *,
    phase: str = 'pre-render',
    source_path: str | None = None,
) -> str:
    """Strip insert-zone directive lines for *phase* and adopt local markers.

    The zone region itself (branded markers plus template default body) is
    never altered here — it flows into the rendered file and becomes the
    insertion phase's fallback content. Zones for the other phase pass through
    untouched so the later pass can process them.
    """
    if not zones:
        return content

    logger.debug('applying_insert_zones', zones=[str(name) for name in zones])
    lines = content.splitlines(keepends=True)
    result: list[str] = []

    for index, line in enumerate(lines):
        stripped = line.rstrip('\r\n')
        match = INSERT_ZONE_DIRECTIVE_RE.match(stripped)
        if match is None:
            result.append(line)
            continue

        raw_name = match.group(1)
        name, directive_phase = split_directive_tag(
            raw_name,
            source_path=source_path,
        )
        if directive_phase != phase:
            # Other phase — the line survives for the later pass to strip.
            result.append(line)
            continue

        spec = zones.get(name)
        if spec is not None and not find_prefixed_bounded_regions(
            lines[index + 1 :],
            spec.boundary,
        ):
            logger.warning(
                'insert_zone_template_region_not_found',
                name=name,
                source_path=source_path,
            )
        continue  # strip the directive line

    return adopt_local_insert_zones(''.join(result), local_content, zones)
