name: ci-checks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup-uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.11'
          activate-environment: true
      - name: mise
        uses: jdx/mise-action@v2
      - name: poe
        run: uv tool install poethepoet
      - name: dependencies
        run: uvx --from poethepoet poe uv-sync
      - name: check-dprint
        run: poe check-dprint
      - name: check-python
        run: poe check-python
      - name: check-basedpyright
        run: poe check-basedpyright
      - name: check-complexity
        run: poe check-complexity
      - name: check-coverage
        run: poe check-coverage
